general:
  name: "Production Ice Chunk - 2024-02_nonhrv.zarr"
  description: "Complete 2024-02_nonhrv.zarr converted to Ice Chunk for production comparison"

input_data:
  satellite:
    icechunk_path: "2024-02_icechunk_full_20250718_154450_962ca20b"
    bucket_name: "gsoc-dakshbir"
    use_true_icechunk: true
    icechunk_branch: "main"
    icechunk_commit: "MCYR0A26NXKMQTWC578G"
    use_optimized_streaming: true
    optimal_time_steps: 6
    optimal_block_size_mb: 64
    channels: ['IR_016', 'IR_039', 'IR_087', 'IR_097', 'IR_108', 'IR_120', 'IR_134', 'VIS006', 'VIS008', 'WV_062', 'WV_073']
    time_resolution_minutes: 15
    interval_start_minutes: -60
    interval_end_minutes: 0
    image_size_pixels_height: 128
    image_size_pixels_width: 128
    normalisation_constants:
      IR_016:
        mean: 0.5
        std: 0.2
      IR_039:
        mean: 0.5
        std: 0.2
      IR_087:
        mean: 0.5
        std: 0.2
      IR_097:
        mean: 0.5
        std: 0.2
      IR_108:
        mean: 0.5
        std: 0.2
      IR_120:
        mean: 0.5
        std: 0.2
      IR_134:
        mean: 0.5
        std: 0.2
      VIS006:
        mean: 0.5
        std: 0.2
      VIS008:
        mean: 0.5
        std: 0.2
      WV_062:
        mean: 0.5
        std: 0.2
      WV_073:
        mean: 0.5
        std: 0.2